name: build

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bin Cache
        uses: actions/cache@v1
        with:
          path: .venv
          key: venv
      - name: Get Vault Token
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          exportToken: true
          method: jwt
          path: github
          role: homechart-python
          secrets: |
            auth/token/lookup-self type
      - name: Build release
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_PATH: ${{ secrets.VAULT_PATH }}
        run: |
          make release
